version: "3"
services:
  frontend:
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - take-home-app
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    image: backend
    ports:
      - "4000:4000"
    networks:
      - take-home-app
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - take-home-app
    volumes:
      - mongo-data:/data/db
networks:
  take-home-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local