
version: '3.1'
volumes:
  mongo_data:
services:
  backend:
    restart: unless-stopped
    image: backend:latest
    ports:
      - 4000:4000
    volumes:
      - ./backend:/user/src/app
    links:
      - mongo
    command: yarn start
    tty: true
    stdin_open: true

  frontend:
    restart: unless-stopped
    image: frontend:latest
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    command: yarn start
    tty: true
    stdin_open: true

  mongo:
    restart: unless-stopped
    image: mongo:3.6.4
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017