
version: '3.1'

volumes:
  mongo_data:

networks:
  app-tier:
    driver: bridge

services:
  backend:
    restart: unless-stopped
    image: backend:latest
    ports:
      - 4000:4000
    volumes:
      - ./backend:/user/src/app
    links:
      - mongo
    command: yarn start
    tty: true
    stdin_open: true
    networks:
      - app-tier

  frontend:
    restart: unless-stopped
    image: frontend:latest
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    command: yarn start
    tty: true
    stdin_open: true
    networks:
      - app-tier

  mongo:
    restart: unless-stopped
    image: bitnami/mongodb:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - app-tier